directories:
  output: release
  buildResources: build
appId: com.easyfinance.app
productName: EasyFinance
files:
  - filter:
      - dist/**
      - main.cjs
      - preload.cjs
      - backend/**
      - jre/**
win:
  target: nsis
extraResources:
  - from: backend/
    to: backend
electronVersion: 39.2.7
